# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.gitignore'
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build-android:
    runs-on: windows-2022
    name: Android Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Install MAUI Workloads
        run: |
          dotnet workload install maui --ignore-failed-sources
          dotnet workload install android --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore JWTrix.sln

      - name: Build MAUI Android
        run: dotnet build JWTrix.sln -c Release -f net7.0-android --no-restore

  build-windows:
    runs-on: windows-2022
    name: Windows Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Install MAUI Workloads
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore JWTrix.sln

      - name: Build MAUI Windows
        # Set `PublishReadyToRun=false` to avoid NETSDK1094 error: https://github.com/dotnet/maui/issues/12100
        run: dotnet build JWTrix.sln -c Release -f net7.0-windows10.0.19041.0 --no-restore -p:PublishReadyToRun=false

  build-ios:
    runs-on: macos-11
    name: iOS Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Install MAUI Workloads
        run: |
          dotnet workload install maui --ignore-failed-sources
          dotnet workload install ios --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore JWTrix.sln

      - name: Build MAUI iOS
        run: dotnet build JWTrix.sln -c Release -f net7.0-ios --no-restore

  build-mac:
    runs-on: macos-12
    name: MacCatalyst Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Install MAUI Workloads
        run: |
          dotnet workload install maui --ignore-failed-sources
          dotnet workload install maccatalyst tvos macos wasm-tools --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore JWTrix.sln

      - name: Build MAUI MacCatalyst
        run: dotnet build JWTrix.sln -c Release --no-restore